### ISSUE TITLE
Test & add support for GHC 8.0

### ISSUE THREAD

**Issue by hvr** [thoughtpolice/hs-ed25519#10]

**Comment by bjpe** [comment]
I just saw that this project is not installable with GHC 8.0 because of the dependency `ghc-prim    >= 0.1 && < 0.5`. However, none of the exported modules of this package are imported and the project could also be configured and built without this dependency.

Thus, it seems to me that it can be removed.

**Comment by hvr** [comment]
@bjpe that's not completely accurate:

``` hs
#if __GLASGOW_HASKELL__ >= 702
import           GHC.Generics             (Generic)
#endif
```

requires `ghc-prim` on some GHC versions. The usual cabal ceremony for that (which is used for instance by `deepseq`) which avoids an unnecessary `ghc-prim` dependency would be:

```
  -- GHC.Generics lived in `ghc-prim` for GHC 7.2 & GHC 7.4
  if impl(ghc >=7.2 && < 7.6)
      build-depends: ghc-prim == 0.2.*
```

**Comment by bjpe** [comment]
Ah, thank you, I did not know that.

**Comment by 23Skidoo** [comment]
@thoughtpolice Can you please also apply the same change to the released version on Hackage? `cabal-install` currently can't be installed on GHC 8 because of this.
