### ISSUE TITLE
Support for deserializing PublicKey and Signature

### ISSUE THREAD

**Issue by runeksvendsen** [thoughtpolice/hs-ed25519#12]
I'm building a server where I need to send signatures and public keys back and forth, in order for the client and server to verify each other's messages. I can send both PublicKeys and Signatures as ByteStrings using unPublicKey and unSignature, respectively, but I cannot construct the original objects back from this serialization, as far as I can see.

**Comment by thoughtpolice** [comment]
Hi,

Sorry for the delayed reply. If I'm understanding correctly, you have `Signature`s and `PublicKey`s, and you can pull the bytestrings out of them easily using their accessors. But you can also easily reconstruct them just by wrapping them in the constructor.

If you're sure you have a `ByteString` that represents a signature (note: this library does not attempt to help you at all with that, just as the underlying implementation doesn't, although it might fail if you do something wrong), just wrap it in `Signature bs` and you have the signature back, of type `Signature`. And just wrap whatever keys you get back in `(PublicKey bs) :: PublicKey`

If this isn't quite what you want, could you give a small code example?

**Comment by runeksvendsen** [comment]
Hello

Thanks for the reply. I had forgotten about this. I the meantime I discovered that I could just use the constructors, as you explain, but I'm somewhat worried that the underlying binary representation might change in a future version of this library, such that this technique all of the sudden may start producing runtime errors, because of invalid PubKey/Sig data.

Would you be willing to add a Binary or Serialize instance of the three basic types (SecretKey, PublicKey and Signature), which would taker over the role of of the "un(SecretKey/PublicKey/Signature)" functions, and with that provide a stable interface for (de)serialization?

Seems to me that serialization and deserialization of particularly a Signature, and also a PublicKey, would be an integral part of using this library in any network protocol (or even writing the data to/from disk).

**Comment by thoughtpolice** [comment]
The basic intention is that any `Signature` or `PublicKey` or `SecretKey` you get as a `ByteString` already _is_ encoded, and there is no 'unencoded' interface to contrast it with. You simply write it out literally, and that is your final value. That is due to the design of Ed25519 itself and should probably be considered more a feature, honestly.

This is because the internal Ed25519 code is what actually does the serialization into the expected formats. And any Ed25519-compatible implementation will basically have to handle this exact format, and it is pretty much already optimal.

For one, Ed25519 secret keys, like Curve25519 secret keys, consist of any arbitrary 32-byte string. Any at all. So generating a [secret key is just a matter of generating some random bytes](https://github.com/floodyberry/supercop/blob/master/crypto_sign/ed25519/ref/keypair.c#L13). But because the string is literally arbitrary, there is no meaningful format to encode it in, the bit pattern of the string itself is all there is.

In fact, the _original_ ed25519 C code is even _more_ opaque than this library is by default, and has a completely opaque interface for key generation and signatures. For example, it does not allow key generation with a seed value (deterministic keygen), as you see in the above code sample. This library instead slightly modifies the code, allowing you to use your own 32-byte value as a key and generate a keypair with that (look at [keypair.c in this repository](https://github.com/thoughtpolice/hs-ed25519/blob/master/src/cbits/ref10/keypair.c) for contrast), or convenient operations like getting the `PublicKey` out of a `SecretKey`. These are easy enough but the original API does not provide them; this library makes many common operations more convenient to do, but doesn't really stray that far from the underlying design.

A `PublicKey` is derived from a SecretKey, as thus: take the hash `H(sk)` of the secret, and 'clamp' it (some clever bitmasks) to the appropriate format to represent a ~256 bit scalar number in the manner Ed25519 specifies. Take this large scalar as a big integer `n`, and then do scalar multiplication against the base point `P` specified for Ed25519. This gives a new point, which you serialize out as the public key. (See the Ed25519 paper.) There is no other format a PublicKey can exist by; this is its definition and it is solely derivable only from the 32-byte secret key.

Similar argument for signatures, etc. The output format is, by definition, the encoded Ed25519 format.

Anyone who strays from all this is probably competent enough with the internals to write their own library or hack this one appropriately. For example, [ed25519 specifies a secret key as containing the public key](https://github.com/floodyberry/supercop/blob/master/crypto_sign/ed25519/ref/keypair.c#L23), so `toPublicKey :: SecretKey -> PublicKey` is a simple `O(1)` `drop` operation to retrieve it. As another example, using the original `crypto_sign` API, reflected with `sign` in this library, [copies the original message into an output buffer, at an offset of 64 bytes, and writes the final signature into the first 64 bytes](https://github.com/floodyberry/supercop/blob/master/crypto_sign/ed25519/ref/sign.c#L29). That means using `crypto_sign` and splitting the message and signature is again, another `O(1)` `drop` - but the format doesn't change at all. We're just returning an opaque blob.

This library _should_ work just fine with any other legitimate Ed25519 implementations. Unless I missed something about formats changing, which _did_ happen with Curve25519 -- but I believe Ed25519's format should be stable at this point (and in fact the Curve25519 format change was partially to help Curve25519-to-Ed25519 key conversion, because Ed25519 is an 'Edwards' curve and not a 'Montgomery' curve, so due to various magical nonsense that means it has an extra bit to keep track of.)

If you _do_ use this library and try to interoperate it with other implementations, the details should mostly be the exact same or pretty similar. E.g. if you use `dsign` in this library, but another language only supports `crypto_sign` itself, you're going to have to either A) write your own library in $OTHERLANG to handle detached signatures, B) use `sign` on your end, or C) use `dsign`, take `Signature`s, and prepend them onto the message they sign (which is essentially equivalent to `sign` itself. Look at the source code for `dsign` vs `sign` in this library to see what I mean, one is derived from another as it stands).

So the very long and short of this is that you should be completely OK to take any of the signatures or keys this library emits and write them out directly. The format they're encoded in is always the exact format defined for Ed25519 (by the original paper and original software), which is common among essentially all implementations and if it doesn't do that, it's a bug. If you use any of the extended interfaces in this package vs the original software, you may have to foot the bill yourself somehow, or restrict yourself to only the common interface.

`Binary` instances for this package are, in general, I think unnecessary. For one, `Binary` for Haskell values essentially defeats the purpose of any common format because serialized Haskell values have no meaning outside Haskell without the original source code, unless you explicitly document it all. Let's say you use something like `putWord32 32 >> putByteString pubKey` to serialize a 32-byte public key. You have to encode the length of an arbitrary `ByteString` in general, so you can get it back later with `getByteString :: Int -> Get ByteString`. This is not the Ed25519 format, so any interoperability requires documenting this. But if you want interoperability, you just have to write the raw `ByteString` out somewhere with nothing else, and you didn't _need_ `Binary` for that! You already have the `ByteString` you need to write.

So, I hope this answers all your questions. Let me know if it does. Please don't close this ticket - it is a legitimate question and clearly a failure that the documentation does not address this point, so I will fix it there once and for all if this all vaguely makes sense.

**Comment by runeksvendsen** [comment]
Thank you for clarifying. I guess I felt like I was doing some sort of "hack" when building eg. a PublicKey using the constructor.

But there's something I still don't understand. How do I verify whether a given PublicKey ByteString (what I get from `unPublicKey`) is actually a valid public key?

So, one end gets the ByteString from a PublicKey using unPublicKey, sends it over the wire, then the other end will want to construct the PublicKey from the ByteString, but if not all 32-byte ByteStrings are valid PublicKeys, how does the other end verify whether or not the constructed PublicKey is valid? The same applies to a Signature.

I assume that not all 32-byte ByteStrings are valid PublicKeys, and that not all 64-byte ByteStrings are valid Signatures. Is this correct? And even so, if I do pass a ByteString of incorrect length to a constructor function, how will it report failure?

The `Crypto.Secp256k1` (https://hackage.haskell.org/package/secp256k1-0.4.5/docs/Crypto-Secp256k1.html) package has a "Maybe" interface for constructing all the basic types, such that I can verify whether the ByteString parses correctly to whatever type I'm trying to create.

So, in essence, when my server receives a supposed PublicKey/Signature ByteString from a client in a message, I would like to be able to verify that this is indeed a valid public key/signature, and it's not clear to me how I can do this.

**Comment by thoughtpolice** [comment]
> How do I verify whether a given PublicKey ByteString (what I get from unPublicKey) is actually a valid public key?

In short: don't. Ed25519 was carefully designed, much like Curve25519, to allow basically arbitrary 32 byte keys. There is no method of verifying the key is 'correctly' formatted or if the public key (which is actually a point on the Ed25519 curve) is valid for any particular signature, without attempting to verify something that you have a signature for.

> I assume that not all 32-byte ByteStrings are valid PublicKeys, and that not all 64-byte ByteStrings are valid Signatures. Is this correct?

Not all of them are valid, but the difference between a 'valid' public key (generated from the random 32 byte seed I talked about earlier, with a corresponding secret key) and just random bytes you generated is immaterial. When you attempt to verify a signed message, if the public key is not the exact public key corresponding to the secret key, which was used to generate the signature - it fails.

So unlike other software, Ed25519, like Curve25519, has no distinguishing or special failure modes. They were both carefully designed to avoid the need to ensure public keys are 'valid' out of the fear of calculating incorrect curve points or other kinds of attacks, or anything like that. You call the signature function with a signed message and the public key, and it always returns 1 or 0. Furthermore, attempting to distinguish between different modes ('bad public key', 'invalid signature', 'invalid length') etc is generally considered error prone and increases costs. It is designed, instead, to be "correct by construction".

If you want this functionality, you will have to build it on top of Ed25519 public keys and signatures. Which is totally doable - just do like GPG and have a parser/serializer that sticks all 32 byte signatures in a

```
---- BEGIN ED25519 SIGNATURE ---
...
---- END ED25519 SIGNATURE ---
```

block. Of course, that's going to be a lot of bloat added onto the 64 byte signature - one of the attractive properties of this choice in the first place is that it's so small! You can do whatever you want. It also adds strictly unnecessary code (unless you need to warn users in the UI about invalid keys or something), which bloats the needed code to implement signing securely. Think carefully about doing this.

> And even so, if I do pass a ByteString of incorrect length to a constructor function, how will it report failure?

Signature verification will always fail, with either an invalid message or signature. Because verification has to deal with possibly hostile inputs, it must always fail no matter what, and it must fail in exactly the same way every time.

```
Prelude Crypto.Sign.Ed25519 Data.ByteString> verify (PublicKey (pack [0x00])) (pack [0x00])
False

Prelude Crypto.Sign.Ed25519 Data.ByteString> dverify (PublicKey (pack [0x00,0x00])) (pack [0x00]) (Signature (pack [0x00]))
False
```

There is no method of determining why a verification fails. It simply always fails.

---

Now, you _did_ find a 'bug' though with `sign`, which doesn't do it's check for a 32-byte string! Nice catch:

```
Prelude Crypto.Sign.Ed25519 Data.ByteString> sign (SecretKey (pack [0x00,00])) (pack [0x00])
"\159|\240W3\208\191\214\155\DELE\180y\221\139d\214\f|\188E\152\227\156\241\249IMW\ETXf7\193\SOH\247\202\236\DLE&\234\140\250\240\193\162\248\&7\SO\172\175%\134o\130\DC3\DLE\SUB<\255Fp\218Y\ENQ\NUL"
Prelude Crypto.Sign.Ed25519 Data.ByteString> sign (SecretKey (pack [0x00,00])) (pack [0x00])
"w\165bBf\147\187\201\152\214c\f#\FS8\208CQ\US\r\235V\146\168v?\253\241@'\228\245cj\220\244\170H\ENQ\173\160\NAK\249,\228\ACK\165\236!bU\164B\167b\NAK!\156f\164\181$r\f\NUL"
```

Signing is supposed to be deterministic, but clearly it is not here. That's because it's probably just grabbing random crap memory off the end of the short `ByteString`, because the C function is just given a `Ptr Word8` and goes to town, assuming the 64-bytes from that pointer are fair game.

So, that should be fixed. I think I have an idea of how to do it, as well.

Now, I say this is a 'bug' with quotes, because this is actually the exact behavior of the original C Ed25519 software. It does not take a 'length' argument for the pointer to the secret key. It simply assumes that pointer points to 64 bytes of allocated memory. You are in fact, expected to assume that the signing process is using a correct key (because if you aren't, anything else implies compromise or irreversible damage to the key anyway which this library could never fix.)

But that's unacceptable for Haskell, so this should be changed. I thought I handled this case but clearly not so. I'll fix it.

But in general I don't think _this_ is the kind of problem you're envisioning - you really really need to always have the right secret key, so this is 'low' on the overall totem pole of "horrible failures" I think, but still bad (especially considering all means of _generating_ a key legitimately do so correctly and safely - only this case was missed). If you were already screwing up your calls to `sign` with an invalid key, things would have gone wrong anyway. It's clearly worse to keep going on than just fail outright, though. But the cases you are worried about otherwise are already handled: verification just fails, end of story.

I hope that answers the rest of your questions.

**Comment by thoughtpolice** [comment]
Oh, and even though that bug with sign exists, I imagine the failure mode is mitigated and rather obvious still, because verifying some bogus signature generated with a bad secret key still fails by definition (it's no different than any other illegitimate signature, or attempted forgery), even if the public key is valid:

```
Prelude Crypto.Sign.Ed25519 Data.ByteString> (pk, sk) <- createKeypair
Prelude Crypto.Sign.Ed25519 Data.ByteString> let msg = pack [0x00, 0x01, 0x02]
Prelude Crypto.Sign.Ed25519 Data.ByteString> dverify pk msg (dsign sk msg)
True
Prelude Crypto.Sign.Ed25519 Data.ByteString> dverify pk msg (dsign (SecretKey $ Data.ByteString.drop 10 $ unSecretKey sk) msg)
False
```

So I don't think this is something that would easily slip by, anyway, since none of your signatures will probably ever work unless you just never test anything ever.

**Comment by runeksvendsen** [comment]
Thank you for your elaborate explanation. I didn't know this is the way Ed25519 worked. It certainly is a lot simpler from the perspective of the library user. And if I need to know whether someone has gone through the trouble of actually deriving a public key, I just need to demand a signature, over some nonce, along with the pubkey in question.
